version: "3"
services:

   trader_python_label:
      container_name: trader_python_container
      image: trader_python_image
      build: 
         context: ./services/python
         args:
            ALPACA_ENDPOINT: ${ALPACA_ENDPOINT}
            ALPACA_KEY: ${ALPACA_KEY}
            ALPACA_SECRET: ${ALPACA_SECRET}
      volumes:
         - ./shared/python:/shared
         - ./scripts:/scripts
      # environment:
      #    - GK_PWD=${PWD}
