version: "3"
services:

   trader_python_label:
      container_name: trader_python_container
      image: trader_python_image
      build: 
         context: ./services/python
      env_file:
         - ./services/python/.env
      volumes:
         - ./shared/python:/shared
         - ./scripts:/scripts
